coffeeshop/coffeeshop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace coffeeshop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

coffeeshop/coffeeshop/Controllers/ProductsController.cs
using coffeeshop.Models.Interfaces;
using coffeeshop.Models.Services;
using Microsoft.AspNetCore.Mvc;

namespace coffeeshop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductRepository _productRepository;

        public ProductsController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        

        public IActionResult Detail(int id)
        {
            var product = _productRepository.GetProductDetail(id);
            if (product != null)
            {
                return View(product);
            }   
            return NotFound();
        }
        public IActionResult Shop()
        {
            var products = _productRepository.GetAllProducts();
            return View(products);
        }
        public IActionResult Trending()
        {
            var trendingProducts = _productRepository.GetTrendingProducts();
            return View(trendingProducts);
        }
    }
}

coffeeshop/coffeeshop/Controllers/ShoppingCartController.cs
using coffeeshop.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
namespace coffeeshop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartRepository shoppingCartRepository;
        private readonly IProductRepository productRepository;


        public ShoppingCartController(IShoppingCartRepository
       shoppingCartRepository, IProductRepository productRepository)
        {
            this.shoppingCartRepository = shoppingCartRepository;
            this.productRepository = productRepository;
        }
        public IActionResult Index()
        {
            var items = shoppingCartRepository.GetAllShoppingCartItems();
            shoppingCartRepository.ShoppingCartItems = items;
            ViewBag.TotalCart = shoppingCartRepository.GetShoppingCartTotal();
            return View(items);
        }
        public RedirectToActionResult AddToShoppingCart(int pId)    
        {

            var product = productRepository.GetAllProducts().FirstOrDefault(p => p.Id ==pId);
            if (product != null)
            {
                shoppingCartRepository.AddToCart(product);
                int cartCount = shoppingCartRepository.GetAllShoppingCartItems().Sum(i => i.Qty);
                HttpContext.Session.SetInt32("CartCount", cartCount);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromShoppingCart(int pId)
        {
            var product = productRepository.GetAllProducts().FirstOrDefault(p => p.Id ==pId);
            if (product != null)
            {
                shoppingCartRepository.RemoveFromCart(product);
                int cartCount = shoppingCartRepository.GetAllShoppingCartItems().Sum(i => i.Qty);
                HttpContext.Session.SetInt32("CartCount", cartCount);
            }
            return RedirectToAction("Index");
        }

    }
}

coffeeshop/coffeeshop/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@{
    var cartCount = HttpContextAccessor?.HttpContext?.Session.GetInt32("CartCount") ?? 0;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v5.7.8, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="assets/images/coffee-icon-sign-symbol-design-free-png.webp" type="image/x-icon">
    <meta name="description" content="">
    <title>Home</title>
    <link rel="stylesheet" href="~/assets/web/assets/mobirise-icons2/mobirise2.css">
    <link rel="stylesheet" href="~/assets/web/assets/mobirise-icons-bold/mobirise￾icons-bold.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="~/assets/parallax/jarallax.css">
    <link rel="stylesheet" href="~/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="~/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="~/assets/theme/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="preload" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"
          as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet"  
              href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900
,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap">
    </noscript>
    <link rel="preload" as="style" href="~/assets/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="~/assets/mobirise/css/mbr-additional.css"
          type="text/css">
</head>
<body>
    <section data-bs-version="5.1" class="menu menu3 cid-tsEQosCCDP mbr-navbar" once="menu" id="menu3-0">
            <nav class="navbar navbar-dropdown navbar-expand-lg">
                <div class="container">
                    <div class="navbar-brand">
                        <span class="navbar-logo">
                            <a asp-controller="Home" asp-action="Index">
                                <img src="~/assets/images/coffee-icon-sign-symbol-design-free-png.webp" alt="Coffee shop"
                                     style="height: 3rem;" />
                            </a>

                        </span>
                    </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse"
                        data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            
                        <div class="hamburger">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">

                        <li class="nav-item">
                            <a class="nav-link link text-black display-4" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link link text-black display-4" asp-controller="Products" asp-action="Shop">Shop</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link link text-black display-4" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link link text-black dropdown-toggle display-4"
                               href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="mobi-mbri mobi-mbri-user-2 mbr-iconfont mbr-iconfont-btn"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item text-black display-4" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-black display-4" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link link text-black display-4" asp-controller="ShoppingCart" asp-action="Index">
                                <span class="mobi-mbri mobi-mbri-shopping-bag mbr-iconfont mbr-iconfont-btn">
                                    <small>(@cartCount)</small>
                                </span>
                            </a>
                        </li>

                    </ul>
                </div>

                </div>

        </nav>
    </section>  
   

    @RenderBody()
    <footer class="text-center py-3 bg-light">
        <p class="mbr-text mb-0 mbr-fonts-style display-7">
            © 2025 - All Rights Reserved
        </p>
    </footer>       
    <script src="~/assets/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/parallax/jarallax.js"></script>
    <script src="~/assets/smoothscroll/smooth-scroll.js"></script>
    <script src="~/assets/ytplayer/index.js"></script>
    <script src="~/assets/dropdown/js/navbar-dropdown.js"></script>
    <script src="~/assets/theme/js/script.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>